// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwWEXSbQBSpnlAiu0k6L7ET0BMX0038tw',
    appId: '1:295368172217:web:8fe8d4bad079a5b5c73168',
    messagingSenderId: '295368172217',
    projectId: 'goilcomplaint',
    authDomain: 'goilcomplaint.firebaseapp.com',
    storageBucket: 'goilcomplaint.firebasestorage.app',
    measurementId: 'G-DFR20C5F38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnm57JkEuJh8nloqYPY_4sHf6gyIkaH_U',
    appId: '1:295368172217:android:5d470bf9f63f6262c73168',
    messagingSenderId: '295368172217',
    projectId: 'goilcomplaint',
    storageBucket: 'goilcomplaint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1WRrlj4E_0CQ4xyqZdLdRKjfgdYvpvwE',
    appId: '1:295368172217:ios:ad74a59046e02d06c73168',
    messagingSenderId: '295368172217',
    projectId: 'goilcomplaint',
    storageBucket: 'goilcomplaint.firebasestorage.app',
    iosBundleId: 'com.ggcomplaintts.gocomplaints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1WRrlj4E_0CQ4xyqZdLdRKjfgdYvpvwE',
    appId: '1:295368172217:ios:ad74a59046e02d06c73168',
    messagingSenderId: '295368172217',
    projectId: 'goilcomplaint',
    storageBucket: 'goilcomplaint.firebasestorage.app',
    iosBundleId: 'com.ggcomplaintts.gocomplaints',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwWEXSbQBSpnlAiu0k6L7ET0BMX0038tw',
    appId: '1:295368172217:web:a5f7a5e04cbeadd1c73168',
    messagingSenderId: '295368172217',
    projectId: 'goilcomplaint',
    authDomain: 'goilcomplaint.firebaseapp.com',
    storageBucket: 'goilcomplaint.firebasestorage.app',
    measurementId: 'G-WL7DQBS3BX',
  );
}
